# Generated by Django 2.1a1 on 2018-06-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=10000)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='this_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.BlogPost'),
        ),
    ]
