# Generated by Django 2.1a1 on 2018-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20180618_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
