# Generated by Django 2.1a1 on 2018-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogpost_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepost',
            name='post',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
