# Generated by Django 2.1a1 on 2018-06-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_auto_20180618_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='post',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_details',
            new_name='post',
        ),
        migrations.DeleteModel(
            name='PostDetails',
        ),
    ]
