# Generated by Django 2.1a1 on 2018-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20180618_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
