# Generated by Django 2.1a1 on 2018-06-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blogpost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_added',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
