# Generated by Django 2.1a1 on 2018-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_blogpost_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.TextField(max_length=10000),
        ),
    ]
