# Generated by Django 2.1a1 on 2018-07-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_auto_20180723_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
    ]
