# Generated by Django 2.1a1 on 2018-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Songs', '0004_auto_20180606_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
