# Generated by Django 2.1a1 on 2018-06-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Songs', '0005_auto_20180606_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_link',
        ),
    ]
