# Generated by Django 2.1a1 on 2018-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Songs', '0010_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
