# Generated by Django 2.1a1 on 2018-06-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Songs', '0008_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
