# Generated by Django 2.1a1 on 2018-06-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1_tutorial', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
