# Generated by Django 2.1a1 on 2018-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
