# Generated by Django 2.1a1 on 2018-06-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blogpost_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10000)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('this_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.BlogPost')),
            ],
        ),
    ]
