# Generated by Django 2.1a1 on 2018-06-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_fuckthis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuckThis',
        ),
    ]
